services:
  nginx:
    image: nginx:alpine
    ports:
      - "8085:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - solomemo

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=solomemo
      - DB_USERNAME=solomemo
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - solomemo

  db:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: solomemo
      MYSQL_USER: solomemo
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - solomemo

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5175:5173"
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - solomemo

networks:
  solomemo:
    driver: bridge

volumes:
  db-data:
